export default {
  immediateVueModelUpdate: true,
  placeholderText: '',
  toolbarInline: true,
  imageUploadParam: 'image',
  imageUploadURL: '/api/editor',
  imageManagerLoadURL: '/api/editor',
  imageManagerDeleteURL: '/api/editor',
  imageManagerDeleteMethod: 'delete',
  htmlAllowedTags: ['p', 'h4', 'h1', 'code', 'ul', 'ol', 'li', 'a', 'img', 'blockquote', 'strong', 'em', 'u', 's'],
  toolbarButtons: [
    'bold',
    'italic',
    'underline',
    'strikeThrough',
    '|',
    'insertLink',
    'insertImage',
  ],
  pluginsEnabled: [
    'lists',
    'quote',
    'link',
    'paragraphFormat',
    'image',
    'imageManager',
  ],
}
