export default {
  key: process.env.FROALA_KEY,
  immediateVueModelUpdate: true,
  placeholderText: '',
  // toolbarInline: true,
  imageUploadParam: 'image',
  imageUploadURL: '/api/editor',
  imageManagerLoadURL: '/api/editor',
  imageManagerDeleteURL: '/api/editor',
  imageManagerDeleteMethod: 'delete',
  htmlAllowedTags: ['p', 'h4', 'h1', 'code', 'ul', 'ol', 'li', 'a', 'img', 'blockquote', 'strong', 'em', 'u', 's'],
  toolbarButtons: [
    'bold',
    'italic',
    'underline',
    'strikeThrough',
    'paragraphFormat',
    'insertLink',
    'quote',
    'formatOL',
    'formatUL',
    /*'insertImage',*/ '|',
    'undo',
    'redo',
    'selectAll'
  ],
  pluginsEnabled: [
    'lists',
    'quote',
    'link',
    'paragraphFormat',
    'image',
    'imageManager',
  ],
}
